namespace: multi-app-demo

apps:
  # PostgreSQL database
  postgres-database:
    type: helm
    enabled: true
    chart: bitnami/postgresql  # repo/chart format (v0.5.0+)
    version: "16.2.4"

    set_values:
      - auth.database=appdb
      - auth.username=appuser
      - auth.password=changeme123
      - primary.resources.requests.memory=256Mi
      - primary.resources.requests.cpu=250m

  # Redis cache
  redis-cache:
    type: helm
    enabled: true
    chart: ot-helm/redis  # OpsTree Redis Operator
    version: "0.15.10"

    set_values:
      - redisCluster.clusterSize=1  # standalone mode
      - kubernetesConfig.image=redis:7.2
      - redisExporter.enabled=false
      - kubernetesConfig.resources.requests.memory=128Mi
      - kubernetesConfig.resources.requests.cpu=100m
