namespace: devops
deps: []

apps:
  - name: browserless-pull
    type: pull-helm
    specs:
      repo: bitnami
      chart: redis
      dest: browserless

  - name: browserless
    type: install-helm
    specs:
      values:
        - browserless.yaml
