# K3scode example - Common sources configuration
# Shared Helm repositories and cluster configuration for all k3scode apps

cluster: k3scode-example
kubeconfig: ~/.kube/config
kubeconfig_context: default

helm_repos:
  # Bitnami charts (Redis, PostgreSQL, MySQL)
  bitnami:
    url: https://charts.bitnami.com/bitnami

  # Grafana ecosystem (Loki, Tempo, etc.)
  grafana:
    url: https://grafana.github.io/helm-charts

  # Prometheus ecosystem
  prometheus-community:
    url: https://prometheus-community.github.io/helm-charts

  # Qdrant (vector database)
  qdrant:
    url: https://qdrant.github.io/qdrant-helm

  # Minio (S3-compatible storage)
  minio:
    url: https://charts.min.io

  # GitLab for DevOps
  gitlab:
    url: https://charts.gitlab.io

git_repos: {}
