cluster: tst-cluster
kubeconfig: ~/.kube/tst-cluster

helm_repos:
  nextcloud: https://nextcloud.github.io/helm/
  minio-official: https://charts.min.io
  seaweedfs: https://seaweedfs.github.io/seaweedfs/helm
  rook: https://charts.rook.io/release
  mattermost: https://helm.mattermost.com
  rocketchat: https://rocketchat.github.io/helm-charts
  argo: https://argoproj.github.io/argo-helm
  gitlab: https://charts.gitlab.io/
  christianhuth: https://christianhuth.github.io/helm-charts
  twuni: https://helm.twun.io
  bitnami: https://charts.bitnami.com/bitnami
  openshift-helm-charts: https://charts.openshift.io/
  prometheus-community: https://prometheus-community.github.io/helm-charts
  grafana: https://grafana.github.io/helm-charts
  kubernetes-dashboard: "https://kubernetes.github.io/dashboard/"
  headlamp: https://headlamp-k8s.github.io/headlamp/
  jaegertracing: https://jaegertracing.github.io/helm-charts
  coredns: "https://coredns.github.io/helm"
  jetstack: "https://charts.jetstack.io"
  traefik: "https://helm.traefik.io/traefik"
  haproxytech: "https://haproxytech.github.io/helm-charts"
  k8s-at-home: "https://k8s-at-home.com/charts/"
  truecharts: https://charts.truecharts.org/
  haproxy-ingress: https://haproxy-ingress.github.io/charts
  cetic: https://cetic.github.io/helm-charts
  apache-airflow: https://airflow.apache.org/
  fiware: https://fiware.github.io/helm-charts/
  fairwinds-stable: https://charts.fairwinds.com/stable
  openfaas: https://openfaas.github.io/faas-netes
  kubernetes-charts: https://charts.helm.sh/stable
  localstack-charts: https://localstack.github.io/helm-charts
  utkuozdemir: https://utkuozdemir.org/helm-charts
  hashicorp: https://helm.releases.hashicorp.com
  harbor: https://helm.goharbor.io
  aquasecurity: https://aquasecurity.github.io/helm-charts/
  sonatype: https://sonatype.github.io/helm3-charts/
  anchore: https://charts.anchore.io
  securecodebox: https://charts.securecodebox.io/
  corecentric: https://codecentric.github.io/helm-charts
  infisical-helm-charts: https://dl.cloudsmith.io/public/infisical/helm-charts/helm/charts/
  istio: https://istio-release.storage.googleapis.com/charts
  renovate: https://docs.renovatebot.com/helm-charts
  elastic: https://helm.elastic.co
  wiremind: https://wiremind.github.io/wiremind-helm-charts
  gradiant-bigdata: https://gradiant.github.io/bigdata-charts
  fluent: https://fluent.github.io/helm-charts
  longhorn: https://charts.longhorn.io
  confluentinc: https://packages.confluent.io/helm
  couchdb: https://apache.github.io/couchdb-helm/
  couchbase: https://couchbase-partners.github.io/helm-charts/
  # https://downloads.apache.org/flink/
  flink-operator-repo: https://downloads.apache.org/flink/flink-kubernetes-operator-1.10.0/
  jenkins: https://charts.jenkins.io
  harness: https://harness.github.io/helm-charts
  drone: https://charts.drone.io
  nfs-subdir-external-provisioner: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
  gitea: https://dl.gitea.io/charts
  temporalio: https://temporalio.github.io/helm-charts
  openobserve: https://charts.openobserve.ai
  sb-proxynd: https://scriptonbasestar.github.io/proxynd/
  sb-helm-charts: https://scriptonbasestar.github.io/sb-helm-charts
  rssnext: https://rssnext.github.io/helm-charts

oci_repos:
  8gears:
    n8n: oci://8gears.container-registry.com/library/n8n
  gabe565:
    rsshub: oci://ghcr.io/gabe565/charts/rsshub

git_repos:
  airflow-fork:
    url: "https://github.com/koustreak/airflow.git"
    branch: "main"
  eck:
    url: "https://github.com/elastic/cloud-on-k8s"
    branch: "2.15"
#    installs:
#      - type: helm
#        path: "deploy/eck-operator"
#      - type: helm
#        path: "deploy/eck-stack"
  istio:
    url: "https://github.com/istio/istio"
    branch: "master"
#    installs:
#      - type: helm
#        path: manifests/charts/base
#      - manifests/charts/istio-control/istio-discovery
#      - manifests/addons
  prometheus-operator:
    url: "https://github.com/prometheus-operator/prometheus-operator.git"
    branch: "main"
#    installs:
#      - "charts/kube-prometheus-stack"
  strimzi:
    url: "https://github.com/strimzi/strimzi-kafka-operator.git"
#    branch: "main"
#    branch: "release-0.45.x"
    branch: "release-0.44.x"
#    installs:
#      - "install/cluster-operator"
  flink:
    url: "https://github.com/apache/flink-kubernetes-operator"
    branch: "release-1.10"
#    installs: helm/flink-kubernetes-operator
#    yaml:
  olm:
    url: "https://github.com/operator-framework/operator-lifecycle-manager.git"
    branch: "master"
  supabase:
    url: "https://github.com/supabase-community/supabase-kubernetes"
    branch: "main"

