namespace: data-pipeline

apps:
  kafka:
    type: helm
    chart: strimzi/strimzi-kafka-operator
    version: "0.45.0"
    values: [values/kafka-values.yaml]

  storage:
    type: yaml
    files: [manifests/storage-pv.yaml]

  spark:
    type: helm
    chart: apache-spark/spark
    version: "2.0.0"
    values: [values/spark-values.yaml]
    depends_on: [kafka, storage]

  demo-pipeline:
    type: yaml
    files: [manifests/pipeline.yaml]
    depends_on: [spark]
