# 클러스터 설정 (필수, v0.4.10+)
cluster: data-pipeline-k3s
kubeconfig: ~/.kube/config
kubeconfig_context: default

# Helm 리포지토리
helm_repos:
  strimzi:
    url: https://strimzi.io/charts/
  apache-spark:
    url: https://apache.github.io/spark-kubernetes-operator/
