namespace: action-demo

apps:
  # CRD 및 Operator 설치 예제
  prometheus-operator-setup:
    type: action
    actions:
      # Step 1: Namespace 생성
      - type: apply
        path: manifests/01-namespace.yaml

      # Step 2: CRD 설치
      - type: apply
        path: manifests/02-crds.yaml

      # Step 3: Operator 배포
      - type: apply
        path: manifests/03-operator.yaml

  # 정리 작업 예제 (비활성화)
  cleanup-example:
    type: action
    enabled: false
    actions:
      - type: delete
        path: manifests/cleanup/old-configmap.yaml
