apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: complex-deps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user
        image: busybox:latest
        command: ["/bin/sh", "-c", "echo 'User Service' && sleep 3600"]
        resources:
          limits:
            memory: 64Mi
            cpu: 50m
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: complex-deps
spec:
  ports:
  - port: 8080
  selector:
    app: user-service
