namespace: multi-ns-demo

apps:
  database:
    type: yaml
    files: [manifests/database.yaml]
    namespace: data

  backend:
    type: yaml
    files: [manifests/backend.yaml]
    namespace: backend
    depends_on: [database]

  frontend:
    type: yaml
    files: [manifests/frontend.yaml]
    namespace: frontend
    depends_on: [backend]
