helm_repos:
  bitnami: https://charts.bitnami.com/bitnami
  prometheus-community: https://prometheus-community.github.io/helm-charts
  grafana: https://grafana.github.io/helm-charts

git_repos:
  example-app:
    url: "https://github.com/example/sample-app.git"
    branch: "main" 