# OCI Registry Example Configuration
# This example demonstrates pulling Helm charts from OCI registries

namespace: devops

apps:
  # TrueCharts Browserless (OCI Registry)
  browserless:
    type: helm
    enabled: true
    chart: browserless/browserless-chrome  # repo/chart format (v0.5.0+)
    version: "1.0.0"  # Specify version if needed
    values:
      - values/browserless.yaml

  # Another OCI chart example (gabe565 charts from GitHub Container Registry)
  uptime-kuma:
    type: helm
    enabled: true
    chart: gabe565/uptime-kuma  # repo/chart format (v0.5.0+)
    version: "2.0.0"
    values:
      - values/uptime-kuma.yaml
