# Kubernetes cluster configuration
kubeconfig: ~/.kube/config
kubeconfig_context: k3d-sbkube
cluster: k3d-sbkube

helm_repos:
  grafana:
    url: https://grafana.github.io/helm-charts
  bitnami:
    url: https://charts.bitnami.com/bitnami
