# SBKube 설정 파일
# 마이그레이션: v0.2.x → SBKube

namespace: data

apps:
  redis:
    type: helm
    chart: bitnami/redis
    # chart_version: 17.13.2
    # app_version: 7.0.12
    values:
      - redis.yaml

  memcached:
    type: helm
    chart: bitnami/memcached
    # chart_version: 7.0.5
    # app_version: 1.6.27
    values:
      - memcached.yaml
