apiVersion: v1
kind: Namespace
metadata: {name: data}
---
apiVersion: apps/v1
kind: Deployment
metadata: {name: database, namespace: data}
spec:
  replicas: 1
  selector: {matchLabels: {app: database}}
  template:
    metadata: {labels: {app: database}}
    spec:
      containers:
      - {name: app, image: hashicorp/http-echo:latest, args: ["-text=Database", "-listen=:5432"], ports: [{containerPort: 5432}]}
---
apiVersion: v1
kind: Service
metadata: {name: database, namespace: data}
spec: {selector: {app: database}, ports: [{port: 5432}]}
