apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kustomize-demo

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development

replicas:
  - name: myapp
    count: 2

images:
  - name: nginx
    newTag: 1.21

configMapGenerator:
  - name: myapp-config
    literals:
      - ENV=development
      - LOG_LEVEL=debug
