apiVersion: apps/v1
kind: Deployment
metadata:
  name: custom-operator
  labels:
    app: custom-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-operator
  template:
    metadata:
      labels:
        app: custom-operator
    spec:
      containers:
      - name: operator
        image: busybox:latest
        command: ["sleep", "3600"]
        env:
        - name: WATCH_NAMESPACE
          value: "example-action"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: custom-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: custom-operator
rules:
- apiGroups: ["example.com"]
  resources: ["myresources"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: custom-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: custom-operator
subjects:
- kind: ServiceAccount
  name: custom-operator
  namespace: example-action 