namespace: complex-deps

apps:
  # === Layer 1: Infrastructure ===

  infra-setup:
    type: action
    actions:
      - type: apply
        path: manifests/namespace.yaml

  # === Layer 2: Data Stores ===

  postgresql:
    type: yaml
    files:
      - manifests/postgresql.yaml
    depends_on:
      - infra-setup

  redis:
    type: yaml
    files:
      - manifests/redis.yaml
    depends_on:
      - infra-setup

  # === Layer 3: Core Services ===

  auth-service:
    type: yaml
    files:
      - manifests/auth-service.yaml
    depends_on:
      - postgresql

  user-service:
    type: yaml
    files:
      - manifests/user-service.yaml
    depends_on:
      - postgresql
      - auth-service  # Auth에 의존

  # === Layer 4: Business Services ===

  order-service:
    type: yaml
    files:
      - manifests/order-service.yaml
    depends_on:
      - postgresql
      - redis
      - user-service

  # === Layer 5: API Gateway ===

  api-gateway:
    type: yaml
    files:
      - manifests/api-gateway.yaml
    depends_on:
      - auth-service
      - user-service
      - order-service

  # === Layer 6: Frontend ===

  frontend:
    type: yaml
    files:
      - manifests/frontend.yaml
    depends_on:
      - api-gateway

  # === Independent: Monitoring ===

  monitoring:
    type: exec
    commands:
      - echo "Setting up monitoring..."
      - kubectl get pods -n complex-deps
    # depends_on 없음 (독립적으로 배포 가능)

  # === Post-deployment ===

  smoke-test:
    type: exec
    commands:
      - echo "=== Running smoke tests ==="
      - sleep 5
      - kubectl get pods -n complex-deps
      - echo "✅ All services deployed"
    depends_on:
      - frontend  # 모든 서비스 배포 후
