architecture: standalone

auth:
  enabled: false

master:
  persistence:
    enabled: false
  resources:
    limits:
      memory: 256Mi
      cpu: 200m
    requests:
      memory: 128Mi
      cpu: 100m
