# SBKube Kustomize Example
# Demonstrates using Kustomize for environment-specific deployments

namespace: kustomize-demo

apps:
  # Development environment
  myapp-dev:
    type: kustomize
    path: overlays/dev
    enabled: true

  # Production environment (disabled by default)
  myapp-prod:
    type: kustomize
    path: overlays/prod
    enabled: false
