apiVersion: apps/v1
kind: Deployment
metadata:
  name: readonly-app
  namespace: rbac-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: readonly-app
  template:
    metadata:
      labels:
        app: readonly-app
    spec:
      serviceAccountName: readonly-sa
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
          limits:
            memory: 128Mi
            cpu: 100m
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployer-app
  namespace: rbac-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployer-app
  template:
    metadata:
      labels:
        app: deployer-app
    spec:
      serviceAccountName: deployer-sa
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
          limits:
            memory: 128Mi
            cpu: 100m
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-config
  namespace: rbac-demo
data:
  message: "RBAC Demo ConfigMap"
