apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: readonly-binding
  namespace: rbac-demo
subjects:
- kind: ServiceAccount
  name: readonly-sa
  namespace: rbac-demo
roleRef:
  kind: Role
  name: readonly-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployer-binding
  namespace: rbac-demo
subjects:
- kind: ServiceAccount
  name: deployer-sa
  namespace: rbac-demo
roleRef:
  kind: Role
  name: deployer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-binding
  namespace: rbac-demo
subjects:
- kind: ServiceAccount
  name: admin-sa
  namespace: rbac-demo
roleRef:
  kind: Role
  name: admin-role
  apiGroup: rbac.authorization.k8s.io
