apiVersion: v1
kind: ServiceAccount
metadata:
  name: readonly-sa
  namespace: rbac-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer-sa
  namespace: rbac-demo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-sa
  namespace: rbac-demo
