apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: yaml-demo
data:
  default.conf: |
    server {
        listen 80;
        server_name _;

        location / {
            return 200 'Hello from SBKube YAML deployment!\n';
            add_header Content-Type text/plain;
        }

        location /health {
            access_log off;
            return 200 'OK';
            add_header Content-Type text/plain;
        }
    }
