namespace: data

apps:
  redis:
    type: helm
    enabled: true
    chart: ot-helm/redis  # OpsTree Redis Operator
    version: "0.15.10"
    values:
      redisCluster:
        clusterSize: 1  # standalone mode
      kubernetesConfig:
        image: redis:7.2
      redisExporter:
        enabled: false
