namespace: data

apps:
  redis:
    type: helm
    enabled: true
    chart: bitnami/redis  # repo/chart format (v0.5.0+)
    version: "19.0.0"
    values:
      architecture: standalone
      auth:
        enabled: false
