apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: dependency-demo
  labels:
    app: frontend
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: frontend
