namespace: enabled-demo

apps:
  # 활성화된 앱 (배포됨)
  redis:
    type: yaml
    files:
      - manifests/redis.yaml
    enabled: true

  # 비활성화된 앱 (건너뜀)
  memcached:
    type: yaml
    files:
      - manifests/memcached.yaml
    enabled: false

  # enabled 생략 (기본값 true, 배포됨)
  postgresql:
    type: yaml
    files:
      - manifests/postgresql.yaml

  # 조건부 기능 (현재 비활성화)
  monitoring:
    type: helm
    chart: prometheus-community/prometheus
    enabled: false
    depends_on:
      - postgresql

  # 실험적 기능 (현재 비활성화)
  experimental-feature:
    type: exec
    enabled: false
    commands:
      - echo "This is an experimental feature"
      - kubectl get pods -n enabled-demo
