apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: linkerd-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: app
        image: hashicorp/http-echo:latest
        args:
        - "-text=Backend Response: OK (mTLS encrypted via Linkerd)"
        - "-listen=:8080"
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 64Mi
            cpu: 50m
        env:
        - name: DATABASE_HOST
          value: "database.linkerd-demo.svc.cluster.local"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: linkerd-demo
spec:
  selector:
    app: backend
  ports:
  - port: 80
    targetPort: 8080
