apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: linkerd-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 128Mi
            cpu: 100m
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: frontend-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-html
  namespace: linkerd-demo
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Linkerd Demo - Frontend</title>
      <style>
        body {
          font-family: Arial, sans-serif;
          max-width: 800px;
          margin: 50px auto;
          padding: 20px;
          background: linear-gradient(135deg, #00D775 0%, #00A8CC 100%);
          color: white;
        }
        .container {
          background: rgba(255, 255, 255, 0.1);
          backdrop-filter: blur(10px);
          border-radius: 20px;
          padding: 40px;
          box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.37);
        }
        h1 { margin: 0 0 20px 0; }
        button {
          background: #00D775;
          color: white;
          border: none;
          padding: 15px 30px;
          border-radius: 10px;
          font-size: 16px;
          cursor: pointer;
          margin: 10px 5px;
        }
        button:hover { background: #00A857; }
        #response {
          background: rgba(255, 255, 255, 0.2);
          padding: 20px;
          border-radius: 10px;
          margin-top: 20px;
          min-height: 50px;
        }
      </style>
    </head>
    <body>
      <div class="container">
        <h1>🔗 Linkerd Service Mesh Demo</h1>
        <p><strong>Frontend Service</strong></p>

        <div>
          <button onclick="callBackend()">Call Backend API</button>
          <button onclick="callDatabase()">Call Database (via Backend)</button>
        </div>

        <div id="response">
          <em>Click buttons to test service-to-service communication...</em>
        </div>

        <h2>✅ Linkerd Features Active:</h2>
        <ul>
          <li>🔒 mTLS: All traffic encrypted automatically</li>
          <li>📊 Metrics: Golden metrics for all services</li>
          <li>🔍 Tracing: Request flow visibility</li>
          <li>⚡ Retries: Automatic retry on failures</li>
        </ul>

        <p style="font-size: 12px; opacity: 0.8;">
          Check your Pod: <code>kubectl get pod -n linkerd-demo</code><br>
          You'll see 2 containers: app + linkerd-proxy
        </p>
      </div>

      <script>
        async function callBackend() {
          const resp = document.getElementById('response');
          resp.innerHTML = '<em>Calling backend...</em>';
          try {
            const response = await fetch('/api/backend');
            const data = await response.text();
            resp.innerHTML = '<strong>Backend Response:</strong><br>' + data;
          } catch(e) {
            resp.innerHTML = '<strong>Error:</strong> ' + e.message;
          }
        }

        async function callDatabase() {
          const resp = document.getElementById('response');
          resp.innerHTML = '<em>Calling backend → database...</em>';
          try {
            const response = await fetch('/api/database');
            const data = await response.text();
            resp.innerHTML = '<strong>Database Response (via Backend):</strong><br>' + data;
          } catch(e) {
            resp.innerHTML = '<strong>Error:</strong> ' + e.message;
          }
        }
      </script>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: linkerd-demo
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
