namespace: rbac-demo

apps:
  # RBAC 리소스 생성
  rbac-resources:
    type: yaml
    files:
      - manifests/serviceaccounts.yaml
      - manifests/roles.yaml
      - manifests/rolebindings.yaml

  # RBAC를 사용하는 애플리케이션
  demo-apps:
    type: yaml
    files:
      - manifests/demo-apps.yaml
    depends_on:
      - rbac-resources
