# 클러스터 설정 (필수, v0.4.10+)
cluster: backup-k3s
kubeconfig: ~/.kube/config
kubeconfig_context: default

# Helm 리포지토리
helm_repos:
  vmware-tanzu:
    url: https://vmware-tanzu.github.io/helm-charts
    description: VMware Tanzu Helm Charts (Velero)
