# Sealed Secrets Controller

fullnameOverride: sealed-secrets-controller

# 컨트롤러 명령어 인자
commandArgs:
  - --update-status

# 리소스 제한
resources:
  requests:
    memory: 128Mi
    cpu: 50m
  limits:
    memory: 256Mi
    cpu: 100m

# RBAC 설정
rbac:
  create: true
  pspEnabled: false

# ServiceAccount
serviceAccount:
  create: true
  name: sealed-secrets-controller

# 서비스
service:
  type: ClusterIP
  port: 8080
