---
# LocalStack - AWS Local Emulator (S3, DynamoDB, etc.)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: dev-env
  labels:
    app: localstack
    component: aws-emulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
        component: aws-emulator
    spec:
      containers:
      - name: localstack
        image: localstack/localstack:3.0
        ports:
        - containerPort: 4566
          name: edge
        - containerPort: 4571
          name: s3
        env:
        - name: SERVICES
          value: "s3,dynamodb,sqs,sns"
        - name: DEBUG
          value: "1"
        - name: DATA_DIR
          value: "/tmp/localstack/data"
        - name: DOCKER_HOST
          value: "unix:///var/run/docker.sock"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        volumeMounts:
        - name: localstack-data
          mountPath: /tmp/localstack
        livenessProbe:
          httpGet:
            path: /_localstack/health
            port: 4566
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_localstack/health
            port: 4566
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: localstack-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: localstack
  namespace: dev-env
  labels:
    app: localstack
spec:
  type: ClusterIP
  ports:
  - port: 4566
    targetPort: edge
    name: edge
  - port: 4571
    targetPort: s3
    name: s3
  selector:
    app: localstack
