# Merge Patch: ConfigMap에 커스텀 설정 추가

data:
  # 기존 데이터는 유지되고, 이 데이터가 추가됨
  custom-dashboard.json: |
    {
      "dashboard": {
        "title": "Custom Dashboard",
        "panels": []
      }
    }

  custom-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Custom Prometheus
        type: prometheus
        url: http://prometheus-server:9090
        access: proxy
        isDefault: false
