# Create Patch: 새로운 ServiceMonitor 리소스 생성

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "prometheus.fullname" . }}-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "prometheus.name" . }}
    chart: {{ include "prometheus.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ include "prometheus.name" . }}
      component: server
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
