# 클러스터 설정 (필수, v0.4.10+)
cluster: database-k3s
kubeconfig: ~/.kube/config
kubeconfig_context: default

# Helm 리포지토리
helm_repos:
  cnpg:
    url: https://cloudnative-pg.github.io/charts
    description: CloudNativePG Operator
