namespace: cost-opt-demo

apps:
  metrics-server:
    type: helm
    chart: metrics-server/metrics-server
    version: "3.12.2"

  demo-app:
    type: yaml
    files: [manifests/app.yaml]
    depends_on: [metrics-server]

  hpa:
    type: yaml
    files: [manifests/hpa.yaml]
    depends_on: [demo-app]

  pdb:
    type: yaml
    files: [manifests/pdb.yaml]
    depends_on: [demo-app]

  resource-quota:
    type: yaml
    files: [manifests/quota.yaml]
