namespace: logging

apps:
  # 1단계: Loki (로그 집계)
  loki:
    type: helm
    chart: grafana/loki
    values:
      - values/loki-values.yaml
    enabled: true

  # 2단계: Promtail (로그 수집, Loki 의존)
  promtail:
    type: helm
    chart: grafana/promtail
    values:
      - values/promtail-values.yaml
    depends_on:
      - loki

  # 3단계: Grafana (시각화, Loki 의존)
  grafana:
    type: helm
    chart: grafana/grafana
    values:
      - values/grafana-values.yaml
    depends_on:
      - loki
