namespace: advanced-overrides-demo

apps:
  # Helm 차트에 고급 커스터마이징을 적용하는 예제
  grafana:
    type: helm
    enabled: true
    chart: grafana/grafana  # repo/chart format (v0.5.0+)
    version: "10.1.2"

    values:
      - grafana-values.yaml

    # 차트 템플릿 파일 전체 교체
    overrides:
      - templates/deployment.yaml  # 사이드카 컨테이너가 포함된 커스텀 Deployment
      - templates/service.yaml     # 추가 포트가 포함된 커스텀 Service

    # 불필요한 파일 삭제
    removes:
      - templates/tests/           # 테스트 리소스 제거
      - templates/serviceaccount.yaml  # ServiceAccount 사용 안 함

    set_values:
      - service.type=LoadBalancer
      - persistence.enabled=false

  # 복잡한 커스터마이징 예제 - Prometheus
  prometheus:
    type: helm
    enabled: true
    chart: prometheus-community/prometheus  # repo/chart format (v0.5.0+)
    version: "25.28.0"

    values:
      - prometheus-values.yaml

    # 보안 강화 및 PVC 커스터마이징
    overrides:
      - templates/server/deploy.yaml   # Security Context가 포함된 Deployment
      - templates/server/pvc.yaml      # 커스텀 PVC 설정

    # 불필요한 컴포넌트 제거
    removes:
      - templates/pushgateway/         # Pushgateway 미사용
      - templates/kube-state-metrics/  # 별도 설치
      - templates/node-exporter/       # 별도 설치

    set_values:
      - server.persistentVolume.enabled=true
      - server.persistentVolume.size=10Gi

  # Glob 패턴 활용 예제 - Redis
  redis:
    type: helm
    enabled: true
    chart: ot-helm/redis  # OpsTree Redis Operator
    version: "0.15.10"

    # Note: OpsTree Redis uses CRDs, removes pattern not applicable
    # Operator automatically manages resources based on configuration

    set_values:
      - redisCluster.clusterSize=1  # standalone mode
      - kubernetesConfig.image=redis:7.2
      - redisExporter.enabled=false
