namespace: exec-demo

apps:
  # 1. 배포 전 검증
  pre-deployment-check:
    type: exec
    commands:
      - echo "=== Pre-deployment Health Check ==="
      - kubectl version --client
      - kubectl cluster-info
      - kubectl get nodes
      - echo "✅ Cluster is ready for deployment"

  # 2. Nginx 배포 (YAML 매니페스트)
  nginx:
    type: yaml
    files:
      - manifests/nginx-deployment.yaml
      - manifests/nginx-service.yaml
    depends_on:
      - pre-deployment-check

  # 3. 배포 후 검증
  post-deployment-verify:
    type: exec
    commands:
      - echo "=== Post-deployment Verification ==="
      - sleep 5
      - kubectl get pods -n exec-demo
      - kubectl get svc -n exec-demo
      - kubectl wait --for=condition=ready pod -l app.kubernetes.io/name=nginx -n exec-demo --timeout=60s
      - echo "✅ Deployment completed successfully"
    depends_on:
      - nginx

  # 4. 정리 작업 (선택적)
  cleanup-failed-pods:
    type: exec
    enabled: false  # 필요시 활성화
    commands:
      - echo "=== Cleaning up failed pods ==="
      - kubectl delete pods --field-selector=status.phase=Failed -n exec-demo --ignore-not-found=true
      - kubectl delete pods --field-selector=status.phase=Succeeded -n exec-demo --ignore-not-found=true
      - echo "✅ Cleanup completed"
