# 클러스터 설정 (필수, v0.4.10+)
cluster: monitoring-k3s
kubeconfig: ~/.kube/config
kubeconfig_context: default

# Helm 리포지토리
helm_repos:
  prometheus-community:
    url: https://prometheus-community.github.io/helm-charts
  grafana:
    url: https://grafana.github.io/helm-charts
