apiVersion: batch/v1
kind: Job
metadata:
  name: pre-install
  namespace: helm-hooks-demo
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - {name: hook, image: busybox:latest, command: ["/bin/sh", "-c", "echo 'Pre-install hook' && sleep 5"]}
