namespace: fullstack

apps:
  # 데이터 레이어
  postgresql:
    type: yaml
    files:
      - manifests/postgresql.yaml
    enabled: true

  redis:
    type: yaml
    files:
      - manifests/redis.yaml
    enabled: true

  # API 레이어
  backend:
    type: yaml
    files:
      - manifests/backend.yaml
    depends_on:
      - postgresql
      - redis
    enabled: true

  # UI 레이어
  frontend:
    type: yaml
    files:
      - manifests/frontend.yaml
    depends_on:
      - backend
    enabled: true

  # 라우팅 레이어
  ingress:
    type: yaml
    files:
      - manifests/ingress.yaml
    depends_on:
      - frontend
    enabled: true
