namespace: linkerd-demo

apps:
  # Linkerd CRDs (먼저 설치 필수)
  linkerd-crds:
    type: helm
    chart: linkerd/linkerd-crds
    namespace: linkerd
    enabled: true

  # Linkerd Control Plane
  linkerd-control-plane:
    type: helm
    chart: linkerd/linkerd-control-plane
    namespace: linkerd
    values:
      - values/linkerd-values.yaml
    depends_on:
      - linkerd-crds
    enabled: true

  # Linkerd Viz (메트릭 및 대시보드)
  linkerd-viz:
    type: helm
    chart: linkerd/linkerd-viz
    namespace: linkerd-viz
    depends_on:
      - linkerd-control-plane
    enabled: true

  # 네임스페이스 설정 (Sidecar 자동 주입)
  namespace-config:
    type: yaml
    files:
      - manifests/namespace.yaml
    depends_on:
      - linkerd-control-plane

  # Demo Microservices
  demo-services:
    type: yaml
    files:
      - manifests/frontend.yaml
      - manifests/backend.yaml
      - manifests/database.yaml
    depends_on:
      - namespace-config
