# 클러스터 설정 (필수, v0.4.10+)
cluster: service-mesh-k3s
kubeconfig: ~/.kube/config
kubeconfig_context: default

# Helm 리포지토리
helm_repos:
  linkerd:
    url: https://helm.linkerd.io/stable
    description: Linkerd Service Mesh official Helm repository
