# SBKube Force Update Example
# Demonstrates using --force option to handle conflicts

namespace: force-demo

apps:
  redis:
    type: helm
    chart: bitnami/redis
    version: 17.13.2
    values:
      - redis.yaml
