apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: sealed-secrets
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        env:
        # Secret에서 환경 변수 주입
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials  # SealedSecret이 생성한 Secret
              key: username
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        # Secret을 파일로 마운트
        volumeMounts:
        - name: secret-volume
          mountPath: /etc/secrets
          readOnly: true
        resources:
          requests:
            memory: 64Mi
            cpu: 50m
          limits:
            memory: 128Mi
            cpu: 100m
      volumes:
      - name: secret-volume
        secret:
          secretName: db-credentials
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: sealed-secrets
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: demo-app
