apiVersion: v1
kind: Service
metadata:
  name: backend-api
  namespace: dependency-demo
  labels:
    app: backend-api
    tier: backend
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: backend-api
