# YAML 타입 앱이 Git 리포지토리 파일을 참조하는 예제
#
# 이 예제는 OLM(Operator Lifecycle Manager)을 설치하는 시나리오입니다.
# 1. olm 앱: Git 리포지토리 클론
# 2. olm-operator 앱: 클론된 리포지토리의 YAML 파일을 참조하여 배포

namespace: infra

apps:
  # 1. Git 리포지토리 클론
  olm:
    type: git
    repo: olm
    branch: master
    enabled: true

  # 2. Git 리포지토리 내부 YAML 파일 참조
  # ${repos.olm} 변수가 .sbkube/repos/olm으로 자동 확장됩니다
  olm-operator:
    type: yaml
    enabled: true
    manifests:
      - ${repos.olm}/deploy/upstream/quickstart/crds.yaml
      - ${repos.olm}/deploy/upstream/quickstart/olm.yaml
    namespace: ""        # 매니페스트 안의 namespace 그대로 사용
    depends_on:
      - olm
