namespace: microservices

apps:
  users-service:
    type: yaml
    files: [manifests/users.yaml]

  orders-service:
    type: yaml
    files: [manifests/orders.yaml]
    depends_on: [users-service]

  products-service:
    type: yaml
    files: [manifests/products.yaml]

  payments-service:
    type: yaml
    files: [manifests/payments.yaml]
    depends_on: [orders-service]

  notifications-service:
    type: yaml
    files: [manifests/notifications.yaml]

  api-gateway:
    type: yaml
    files: [manifests/gateway.yaml]
    depends_on:
      - users-service
      - orders-service
      - products-service
      - payments-service
      - notifications-service
