# sources.yaml - Multi-App Groups Auto-Discovery
# 이 예제는 자동 탐색 기능을 사용하여 여러 앱 그룹을 배포합니다.

kubeconfig: ~/.kube/config
kubeconfig_context: default

# app_dirs를 지정하지 않으면 자동으로 모든 config.yaml이 있는 디렉토리를 탐색합니다.
# 이 경우 frontend/, backend/, database/ 세 그룹이 자동으로 발견됩니다.

helm_repos:
  bitnami:
    url: https://charts.bitnami.com/bitnami
