apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kustomize-demo

bases:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: production

replicas:
  - name: myapp
    count: 5

images:
  - name: nginx
    newTag: 1.25

configMapGenerator:
  - name: myapp-config
    literals:
      - ENV=production
      - LOG_LEVEL=info

patchesStrategicMerge:
  - resources-patch.yaml
