# Redis values (기본값 - 환경별 오버라이드)

architecture: standalone

auth:
  enabled: false

master:
  persistence:
    enabled: true
    size: 2Gi

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
