namespace: git-demo

apps:
  # Git 리포지토리 클론
  chart-source:
    type: git
    repo: example-charts
    path: charts

  # 클론된 차트 사용
  example-app:
    type: helm
    chart: ./repos/example-charts/charts/nginx
    values:
      - example-values.yaml
    depends_on:
      - chart-source
