# 클러스터 설정 (필수, v0.4.10+)
cluster: local-k3s
kubeconfig: ~/.kube/config
kubeconfig_context: default

# Git 리포지토리
git_repos:
  example-charts:
    url: https://github.com/example/helm-charts.git
    branch: main
