# SBKube Configuration
# Example: Deploy YAML manifests

namespace: example-yaml

apps:
  nginx:
    type: yaml
    files:
      - manifests/nginx-deployment.yaml
      - manifests/nginx-service.yaml
    namespace: example-yaml
