namespace: ingress-demo

apps:
  # k3s Traefik은 이미 설치되어 있음 (noop으로 표현)
  traefik:
    type: noop
    description: "k3s 기본 Traefik IngressController"

  # 데모 애플리케이션
  demo-apps:
    type: yaml
    files:
      - manifests/apps.yaml
    depends_on:
      - traefik

  # Traefik 미들웨어
  middlewares:
    type: yaml
    files:
      - manifests/middlewares.yaml
    depends_on:
      - demo-apps

  # IngressRoute
  ingress-routes:
    type: yaml
    files:
      - manifests/ingress-routes.yaml
    depends_on:
      - middlewares
