namespace: helm-custom

apps:
  # 1. Release Name + Set Values (Dev)
  nginx-dev:
    type: helm
    chart: ingress-nginx/ingress-nginx
    version: "4.12.0"
    release_name: nginx-dev  # Helm 릴리스 이름 커스터마이징
    values:
      - values/base-values.yaml
      - values/dev-values.yaml
    set_values:
      # CLI 값 오버라이드 (values 파일보다 우선)
      controller.replicaCount: "1"
      controller.resources.limits.memory: "256Mi"

  # 2. 다른 릴리스 (Staging)
  nginx-staging:
    type: helm
    chart: ingress-nginx/ingress-nginx
    version: "4.12.0"
    release_name: nginx-staging
    values:
      - values/base-values.yaml
      - values/staging-values.yaml
    set_values:
      controller.replicaCount: "2"
      controller.service.type: "LoadBalancer"

  # 3. Production 릴리스 (HA Mode)
  nginx-prod:
    type: helm
    chart: ingress-nginx/ingress-nginx
    version: "4.12.0"
    release_name: nginx-prod
    values:
      - values/base-values.yaml
      - values/prod-values.yaml
    set_values:
      controller.replicaCount: "3"
      controller.autoscaling.enabled: "true"
      controller.autoscaling.maxReplicas: "10"
