# sources.yaml with explicit app_dirs list
# This example demonstrates how to control which app directories are deployed

kubeconfig: "~/.kube/config"
kubeconfig_context: "minikube"

# Optional: Explicit list of app directories to deploy (v0.5.0+)
# If not specified, all directories with config.yaml will be auto-discovered
app_dirs:
  - redis
  - postgres
  # nginx is excluded from deployment

helm_repos:
  bitnami:
    url: https://charts.bitnami.com/bitnami
