namespace: dr-demo

apps:
  velero:
    type: helm
    chart: vmware-tanzu/velero
    namespace: velero

  backup-schedule:
    type: yaml
    files: [manifests/schedule.yaml]
    depends_on: [velero]

  recovery-plan:
    type: yaml
    files: [manifests/recovery.yaml]
    depends_on: [backup-schedule]
