# SBKube 예제: Overrides 및 Removes 사용

namespace: demo

apps:
  redis:
    type: helm
    chart: bitnami/redis
    version: 17.13.2
    values:
      - redis.yaml

    # Overrides: overrides/redis/ 디렉토리의 파일로 차트 파일 교체
    overrides:
      - values.yaml           # values.yaml을 커스텀 버전으로 교체
      - templates/service.yaml # service.yaml을 커스텀 버전으로 교체

    # Removes: 빌드 시 불필요한 파일/디렉토리 제거
    removes:
      - README.md
      - templates/ingress.yaml

    # Labels 및 Annotations
    labels:
      app.kubernetes.io/managed-by: sbkube
      environment: demo
    annotations:
      sbkube.io/version: "0.3.0"

    # Helm 옵션
    create_namespace: true
    wait: true
    timeout: 10m
    atomic: true
