namespace: helm-demo

apps:
  # 원격 Helm 차트 예제 - Grafana (공식)
  grafana:
    type: helm
    chart: grafana/grafana
    version: "10.1.2"
    values:
      - grafana-values.yaml

  # 차트 커스터마이징 예제 - Prometheus (공식)
  prometheus:
    type: helm
    chart: prometheus-community/prometheus
    version: "25.28.0"
    values:
      - prometheus-values.yaml
