# Prometheus base values (공통 설정)

server:
  persistentVolume:
    enabled: true
    size: 8Gi

  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi

alertmanager:
  enabled: true
