# sources.yaml - Default (Production) Environment
# 기본(프로덕션) 환경 클러스터 설정

cluster: production-k3s
kubeconfig: ~/.kube/config
kubeconfig_context: default

helm_repos:
  grafana:
    url: https://grafana.github.io/helm-charts
  prometheus-community:
    url: https://prometheus-community.github.io/helm-charts
  ot-helm:
    url: https://ot-container-kit.github.io/helm-charts/
