path: proxy/apt

#cache:
#  enabled: false
#  retention_time: 1h
#  evict: 1h

proxies:
  ubuntu:
    - name: official
      url: http://archive.ubuntu.com/ubuntu
    - name: kakao
      url: http://mirror.kakao.com/ubuntu
    - name: ubuntu-security
      url: http://security.ubuntu.com/ubuntu
  debian:
    - name: official
      url: http://ftp.debian.org/debian
