apiVersion: apps/v1
kind: Deployment
metadata:
  name: insecure-app
  namespace: podsec-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: insecure-app
  template:
    metadata:
      labels:
        app: insecure-app
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        resources:
          limits:
            memory: 128Mi
            cpu: 100m
