namespace: sealed-secrets

apps:
  # 1단계: Sealed Secrets Controller 설치
  sealed-secrets-controller:
    type: helm
    chart: sealed-secrets/sealed-secrets
    values:
      - values/sealed-secrets-values.yaml
    enabled: true

  # 2단계: SealedSecret 리소스 생성 (Controller 의존)
  demo-sealed-secrets:
    type: yaml
    files:
      - manifests/sealed-secret.yaml
    depends_on:
      - sealed-secrets-controller

  # 3단계: Secret을 사용하는 애플리케이션 (SealedSecret 의존)
  demo-app:
    type: yaml
    files:
      - manifests/demo-app.yaml
    depends_on:
      - demo-sealed-secrets
