namespace: http-demo

apps:
  # 예제 1: 공개 매니페스트 다운로드 (실제 URL은 예시용)
  download-example-crd:
    type: http
    url: https://raw.githubusercontent.com/kubernetes/examples/master/staging/pod
    dest: downloaded/example-crd.yaml

  # 예제 2: 다운로드한 파일 배포
  deploy-crd:
    type: action
    actions:
      - type: apply
        path: downloaded/example-crd.yaml
    depends_on:
      - download-example-crd

  # 예제 3: 여러 파일 다운로드
  download-configmap:
    type: http
    url: https://k8s.io/examples/configmap/configmap-multikeys.yaml
    dest: downloaded/configmap.yaml

  download-deployment:
    type: http
    url: https://k8s.io/examples/application/deployment.yaml
    dest: downloaded/deployment.yaml

  # 예제 4: YAML 타입으로 배포
  deploy-all:
    type: yaml
    files:
      - downloaded/configmap.yaml
      - downloaded/deployment.yaml
    depends_on:
      - download-configmap
      - download-deployment
