# 커스텀 values.yaml (overrides)
# 원본 values.yaml을 이 파일로 교체

auth:
  enabled: false

master:
  persistence:
    enabled: false
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi

replica:
  replicaCount: 0
