# SBKube Configuration - Basic Example
# This demonstrates the simplest way to deploy applications with SBKube

# Default namespace for all apps (can be overridden per app)
namespace: demo

# Application definitions
# Each app is a key-value pair where the key is the app name
apps:
  # Example 1: Deploy Redis from Bitnami Helm repository
  redis:
    type: helm                        # Application type: helm chart
    chart: bitnami/redis              # Format: repo/chart
    version: "17.13.2"                # Optional: specific chart version
    values:                           # Optional: values file(s) to override defaults
      - redis.yaml

  # Example 2: Deploy PostgreSQL database
  postgresql:
    type: helm
    chart: bitnami/postgresql
    namespace: database               # Override global namespace for this app
    values:
      - postgres.yaml
    depends_on:                       # Optional: deployment order
      - redis                         # Deploy after redis

  # Example 3: Deploy from local Helm chart
  my-local-app:
    type: helm
    chart: ./local-chart              # Path to local chart directory
    enabled: false                    # Disabled by default (set to true to deploy)
