# 클러스터 설정 (필수, v0.4.10+)
cluster: message-queue-k3s
kubeconfig: ~/.kube/config
kubeconfig_context: default

# Helm 리포지토리
helm_repos:
  rabbitmq:
    url: https://charts.rabbitmq.com/
    description: RabbitMQ Cluster Operator
