namespace: multi-cluster-demo

apps:
  cluster-config:
    type: yaml
    files: [manifests/clusters.yaml]

  federated-app:
    type: yaml
    files: [manifests/federated-deployment.yaml]
    depends_on: [cluster-config]
